api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
    # Global redirect from HTTP to HTTPS automatically
    http:
      redirections:
        entrypoint:
          # Matches the entryPoint below
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: $URL
            sans: "*$URL"
          - main: $INTERNAL_URL
            sans: "*.$INTERNAL_URL"
      

providers:
  docker:
    network: traefik_proxy
    endpoint: "unix:///var/run/docker.sock"

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${EMAIL}
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
