version: '3.6'
services:
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    hostname: bitwarden.${URL}
    restart: always
    volumes:
      - ~/.bitwarden:/data
    networks:
      - traefik_proxy
    labels:
      - traefik.http.routers.bitwarden-ui.rule=Host(`bitwarden.${URL}`)
      - traefik.http.routers.bitwarden-ui.entrypoints=https
      - traefik.http.routers.bitwarden-ui.service=bitwarden-ui
      - traefik.http.routers.bitwarden-ui.tls=true
      - traefik.http.routers.bitwarden-ui.tls.certresolver=letsencrypt
      - traefik.http.services.bitwarden-ui.loadbalancer.server.port=80
      - traefik.http.routers.bitwarden-websocket.rule=Host(`bitwarden.${URL}`) && Path(`/notification/hub`)
      - traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket
      - traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012
      - svc.tier=core
      - svc.stack=home

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
