version: '3.5'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ~/.dockerServices/homeassistant:/config
    restart: unless-stopped
    #networks:
    #  - traefik_proxy
    network_mode: host
    #ports:
    #  - 8123:8123
    expose:
      - 8123
    environment:
      - TZ=Pacific/Auckland
    privileged: true
    labels:
      - traefik.http.routers.homeassistant.rule=Host(`ha.${URL}`)
      - traefik.http.routers.homeassistant.entrypoints=https
      - traefik.http.routers.homeassistant.tls=true
      - traefik.http.routers.homeassistant.service=homeassistant
      - traefik.http.routers.homeassistant.tls.certresolver=letsencrypt
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
    extra_hosts:
      - host.docker.internal:172.17.0.1

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
