services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    volumes:
      - /home/nathan/.dockerServices/jellyfin/config:/config
      - /home/nathan/.dockerServices/jellyfin/cache:/cache
      - /mnt/lacie/Television:/tv1:ro
      - /mnt/lacie/Movies:/movies1:ro
      - /mnt/media/Videos/Television:/tv2:ro
      - /mnt/mini/Videos/Movies:/movies2:ro
      - /mnt/mini/Music:/music:ro
    restart: "unless-stopped"
    # ports:
    #   - 8920:8920 #optional
    #   - 7359:7359/udp #optional
    #   - 1900:1900/udp #optional
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${URL}
    networks:
      - traefik_proxy
    labels:
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${URL}`)
      - traefik.http.routers.jellyfin.entrypoints=https
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.tls.certresolver=letsencrypt
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

networks:
  traefik_proxy:
    external:
      name: traefik_proxy

