version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always
    labels:
      - svc.tier=core
      - svc.stack=plausible

  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    labels:
      - svc.tier=core
      - svc.stack=plausible

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    labels:
      - svc.tier=core
      - svc.stack=plausible

  plausible:
    container_name: plausible
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    env_file:
      - ../config/plausible-config.env
    labels:
      - traefik.http.routers.plausible.rule=Host(`plausible.${URL}`)
      - traefik.http.routers.plausible.entrypoints=https
      - traefik.http.routers.plausible.tls=true
      - traefik.http.routers.plausible.tls.certresolver=letsencrypt
      - traefik.http.services.plausible.loadbalancer.server.port=8000
      - svc.tier=core
      - svc.stack=plausible

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local

networks:
  default:
    external:
      name: traefik_proxy
