version: '3.6'
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    hostname: portainer.ndser.page
    restart: always
    volumes:
      - ~/.config/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    networks:
      - traefik_proxy
    labels:
      - traefik.http.routers.portainer.rule=Host(`portainer.${URL}`)
      - traefik.http.routers.portainer.entrypoints=https
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=letsencrypt
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - svc.tier=dev
      - svc.stack=home

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
